name: CI pipeline

on:
  pull_request:
    branches:
      - main

env:
  HUSKY: 0

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
